version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  groups:
    jdt:
      patterns:
        - "org.eclipse.jdt:org.eclipse.jdt.core"
    maven:
      patterns:
        - "*"
  ignore:
    # ignore transitive dependencies updated with src/build/find-transitive-eclipse-updates.sh
    - dependency-name: "org.eclipse.platform:*"
    - dependency-name: "org.eclipse.jdt:ecj"
    - dependency-name: "org.osgi:*"
    - dependency-name: org.codehaus.plexus:plexus-xml
      versions:
      - ">=4.0.0"
    - dependency-name: org.slf4j:slf4j-simple
      version:
      - ">=2.0.0"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  groups:
    github-actions:
      patterns:
        - "*"
