language: java

jdk:
  - oraclejdk8
  - oraclejdk7
   
env:
  global:
     - secure: Tjp3/Ai1c8Logfc8TfzcCT1L6GYn+kbXg9DM4e9bNoNL7TlhjPadfI15a941RF5RP1T/Y9vh1WqNwJzy5TJQBjA52azSRg0B51AaJd++V77duSKkD2LtyeoJOoG3duNp8uQni8jKfms8cIjQ+ib4V8vGwiYRCpie4aIc388o8mQ2f9U7PGvXMW2ewkZelwMZIa7Lr896JH1mTzseYTUrav6d++vzK/t9yv5pIPq9JULBAAHn7ncFcaNsCqb4k2MiVQ0diA9CTeiaynfDxVEP+71MHSHmkji3MEwgn3LFx1qFgQaE+2J8shiBiBr7lTT7rq6kLxaCnqinmufiWk6q3g==

install:
  - echo 'skipping'

script:
  - mvn install -B -T10

after_success:
  - mvn resources:resources jacoco:merge jacoco:report coveralls:report -DrepoToken=$COVERALLS_REPO_KEY -Pcoveralls -N -B
