language: java

os:
  - linux

jdk:
  - oraclejdk8

install:
  - mvn dependency:go-offline -Pci,skip-formatter -DskipTests=true -q -fn
  - mvn install -Pci,skip-formatter -DskipTests=true -q -fn

script:
  - mvn clean install -Pci -B
